pull_request_rules:
  - name: yaml-deser-test
    conditions:
      - base=main
    actions:
      comment:
        message: |
          yaml deser test result: {{ title }}
      label:
        add:
          - "test-label"
