pull_request_rules:
  - name: gs-verify
    conditions:
      - label=gs-verify
    actions:
      comment:
        message: |
          GSVERIFY-START
          section=[{{ body | get_section("## Summary") }}]
          GSVERIFY-END
